[project]
name = "django-blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django==5.1.2",
    "pillow==10.4.0",
    "python-dotenv==1.0.1",
]
